### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by Bra1nsen** [adafruit/Adafruit_CircuitPython_LTR390#10]
after: sudo python setup.py install
----------------------------------------------------------

/usr/local/lib/python3.7/dist-packages/setuptools_scm/integration.py:38: RuntimeWarning:
ERROR: setuptools==40.8.0 is used in combination with setuptools_scm>=6.x

Your build configuration is incomplete and previously worked by accident!

This happens as setuptools is unable to replace itself when a activated build dependency
requires a more recent setuptools version
(it does not respect "setuptools>X" in setup_requires).

setuptools>=31 is required for setup.cfg metadata support
setuptools>=42 is required for pyproject.toml configuration support

Suggested workarounds if applicable:
 - preinstalling build dependencies like setuptools_scm before running setup.py
 - installing setuptools_scm using the system package manager to ensure consistency
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  """
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    py_modules=["adafruit_ltr390"],
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 739, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/local/lib/python3.7/dist-packages/setuptools_scm/integration.py", line 65, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/usr/local/lib/python3.7/dist-packages/setuptools_scm/__init__.py", line 177, in _get_version
    parsed_version = _do_parse(config)
  File "/usr/local/lib/python3.7/dist-packages/setuptools_scm/__init__.py", line 143, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/home/pi/LTR390_'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
------------------------------------------------------------
do i have to edit the setup.py file ? What iam missing here?

**Comment by Bra1nsen** [comment]
ah okay fixed it with: python -m pip install pyproject.toml
 that was new for me!
