### ISSUE TITLE
adafruit_ltr390 not working

### ISSUE THREAD

**Issue by KurtHofman** [adafruit/Adafruit_CircuitPython_LTR390#5]
When I try to run the test-code I get an error.

Board : Feather S2

Code : 
import time
import board
import adafruit_ltr390

i2c = board.I2C()
ltr = adafruit_ltr390.LTR390(i2c)

while True:
    print("UV:", ltr.uvs, "\t\tAmbient Light:", ltr.light)
    print("UVI:", ltr.uvi, "\t\tLux:", ltr.lux)
    time.sleep(1.0)

Error : 
code.py output:
Traceback (most recent call last):
  File "code.py", line 6, in <module>
  File "adafruit_ltr390.py", line 254, in __init__
  File "adafruit_ltr390.py", line 260, in initialize
  File "adafruit_ltr390.py", line 283, in _reset
  File "adafruit_register/i2c_bit.py", line 43, in __get__
  File "adafruit_register/i2c_bit.py", line 43, in __get__
OSError: [Errno 5] Input/output error

Code done running.

**Comment by ladyada** [comment]
hi this could be a wiring error - please post in the feather s2 forums to get help :)
